# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=100)),
                ('chunk_size', models.IntegerField()),
                ('time_stamp', models.CharField(max_length=20)),
            ],
        ),
    ]
